# Generated by Django 4.2.1 on 2023-05-18 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0004_pricing_productreview_delete_dummy_and_more"),
        ("core", "0003_address_membership_userrewardlog_delete_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "order_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("total_count", models.IntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "paid"),
                            (2, "shipped"),
                            (3, "received"),
                            (4, "evaluated"),
                            (5, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("trade_no", models.CharField(default="", max_length=128)),
                (
                    "addr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "coupon_code",
                    models.CharField(
                        default="215DD",
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_unit",
                    models.CharField(
                        choices=[("t", "Toman"), ("p", "Percent")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("valid_until", django_jalali.db.models.jDateTimeField()),
                ("expired", models.BooleanField(default=False)),
                ("minimum_order_value", models.IntegerField()),
                ("maximum_discount_amount", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                ("count", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comment", models.CharField(default="", max_length=256)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.orderinfo"
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.subproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryDiscount",
            fields=[
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "coupon_code",
                    models.CharField(
                        default="215DD",
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_unit",
                    models.CharField(
                        choices=[("t", "Toman"), ("p", "Percent")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("valid_until", django_jalali.db.models.jDateTimeField()),
                ("expired", models.BooleanField(default=False)),
                ("minimum_order_value", models.IntegerField()),
                ("maximum_discount_amount", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
