# Generated by Django 4.2.1 on 2023-05-23 06:49

from django.db import migrations, models
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "coupon_code",
                    models.CharField(
                        default="53A0A", editable=False, max_length=50, unique=True
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_unit",
                    models.CharField(
                        choices=[("t", "Toman"), ("p", "Percent")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("valid_until", django_jalali.db.models.jDateTimeField()),
                ("expired", models.BooleanField(default=False)),
                ("minimum_order_value", models.IntegerField()),
                ("maximum_discount_amount", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.UUID("a5e3e833-66a3-4e3b-ac95-88ed2bf99377"),
                        editable=False,
                        unique=True,
                    ),
                ),
                ("total_count", models.IntegerField(default=1, editable=False)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "paid"),
                            (2, "shipped"),
                            (3, "received"),
                            (4, "evaluated"),
                            (5, "Completed"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                ("count", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                (
                    "coupon_code",
                    models.CharField(
                        default="53A0A", editable=False, max_length=50, unique=True
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_unit",
                    models.CharField(
                        choices=[("t", "Toman"), ("p", "Percent")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("valid_until", django_jalali.db.models.jDateTimeField()),
                ("expired", models.BooleanField(default=False)),
                ("minimum_order_value", models.IntegerField()),
                ("maximum_discount_amount", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
