# Generated by Django 4.2.1 on 2023-05-18 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
        ("core", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscount",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.orderinfo"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.subproduct"
            ),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.address"
            ),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="categorydiscount",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.category"
            ),
        ),
    ]
