# Generated by Django 4.2.1 on 2023-05-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscount",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.orderinfo"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.subproduct"
            ),
        ),
    ]
