# Generated by Django 4.2.1 on 2023-05-23 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinfo",
            name="addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.address"
            ),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="categorydiscount",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.category"
            ),
        ),
    ]
