# Generated by Django 4.2.1 on 2023-05-23 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="C157B", editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("27ebcacf-b26e-4cf8-878b-ede9c6f23eed"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="C157B", editable=False, max_length=50, unique=True
            ),
        ),
    ]
