# Generated by Django 4.2.1 on 2023-05-25 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_categorydiscount_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydiscount',
            name='coupon_code',
            field=models.CharField(default='A7BBA', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('3bcfcf3e-be98-4bfc-a7a4-bca200265922'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='coupon_code',
            field=models.CharField(default='A7BBA', editable=False, max_length=50, unique=True),
        ),
    ]
