# Generated by Django 4.2.1 on 2023-05-22 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_categorydiscount_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="2B828",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("05b12ef2-e51f-470c-9599-8ef9579308b4"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="2B828",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
