# Generated by Django 4.2.1 on 2023-06-02 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_categorydiscount_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydiscount',
            name='coupon_code',
            field=models.CharField(default='CBA93', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('262e4900-08f3-4b51-86c2-2aa871fa74d1'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='coupon_code',
            field=models.CharField(default='CBA93', editable=False, max_length=50, unique=True),
        ),
    ]
