# Generated by Django 4.2.1 on 2023-05-18 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_alter_categorydiscount_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="F6A48",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("19f637f4-972c-4e90-958a-caa49bde6c8c"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="F6A48",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
