# Generated by Django 4.2.1 on 2023-06-02 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_categorydiscount_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydiscount',
            name='coupon_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('dba78e57-d1bf-49b9-b16f-d1f782a4e118'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='coupon_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
