# Generated by Django 4.2.1 on 2023-05-18 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_alter_categorydiscount_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="9BC4C",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("c2cd1629-a6f5-4139-b136-20cb4266ef28"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="total_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="9BC4C",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
