# Generated by Django 4.2.1 on 2023-06-02 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_categorydiscount_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydiscount',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='coupon_code',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('086b2424-5eaa-4ba3-8dbd-2697dcce493b'), editable=False, unique=True),
        ),
    ]
