# Generated by Django 4.2.1 on 2023-05-18 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_alter_categorydiscount_coupon_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinfo",
            name="trade_no",
        ),
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="EC0E1",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("ab434649-83b0-4e8d-b6e6-8042aba86157"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="EC0E1",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
