# Generated by Django 4.2.1 on 2023-05-18 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0013_remove_orderinfo_trade_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="comment",
        ),
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="7DFEF",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("1cb6c4ca-09df-4d83-8eda-bafc58e4e73b"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="7DFEF",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
