# Generated by Django 4.2.1 on 2023-06-03 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_orderinfo_order_id_alter_orderinfo_total_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('02bf99f2-d5fc-4689-a34b-32f368451d32'), editable=False, unique=True),
        ),
    ]
