# Generated by Django 4.2.1 on 2023-05-18 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0014_remove_orderitem_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="913C3",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("686eedba-478d-408f-b71b-2574c5202101"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="total_count",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="913C3",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
