# Generated by Django 4.2.1 on 2023-05-18 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0015_alter_categorydiscount_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorydiscount",
            name="coupon_code",
            field=models.CharField(
                default="05A68",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="orderinfo",
            name="order_id",
            field=models.UUIDField(
                default=uuid.UUID("412d2375-8f88-4b27-bee6-4c4617274400"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="coupon_code",
            field=models.CharField(
                default="05A68",
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
