# Generated by Django 4.2.1 on 2023-06-03 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sku',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('97d078db-f5b9-458d-8dec-87d2c2168e1e'), editable=False, unique=True),
        ),
    ]
