# Generated by Django 4.2.1 on 2023-06-03 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_rename_sku_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('fbdf710e-f544-4998-83da-2123129ad3f4'), editable=False, unique=True),
        ),
    ]
