# Generated by Django 4.2.1 on 2023-06-03 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_remove_orderitem_price_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('54924c3b-2113-47bd-8f1c-42fe02551c36'), editable=False, unique=True),
        ),
    ]
