# Generated by Django 4.2.1 on 2023-06-03 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_media_options'),
        ('cart', '0018_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydiscount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('34466b10-ceef-4c90-a4f4-26b705093971'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='shop.product'),
        ),
    ]
