# Generated by Django 4.2.1 on 2023-06-03 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_categorydiscount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('bad2f20e-e518-4055-a81a-89ac46e998a1'), editable=False, unique=True),
        ),
    ]
