# Generated by Django 4.2.1 on 2023-06-12 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_orderinfo_addr_alter_orderinfo_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('a67ff20c-0797-49ea-a816-5a5af4200b74'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
