# Generated by Django 4.2.1 on 2023-06-13 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_orderinfo_order_id_alter_orderitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('a3846732-3e28-4b4b-8999-b440cf1df411'), editable=False, unique=True),
        ),
    ]
