# Generated by Django 4.2.1 on 2023-06-14 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydiscount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('7722b37f-ac50-481e-bc7f-635a387049da'), editable=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
