# Generated by Django 4.2.1 on 2023-06-14 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_categorydiscount_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('0a5df88f-9109-4a2b-a1a5-3a50856db93a'), editable=False),
        ),
    ]
