# Generated by Django 4.2.1 on 2023-06-14 22:21

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscount',
            name='code',
            field=models.CharField(default=43433, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='code',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='maximum_discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='minimum_order_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorydiscount',
            name='valid_until',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('1cb538fb-8ba4-450a-b4ad-7eeba17b018e'), editable=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='maximum_discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='minimum_order_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='valid_until',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_date', django_jalali.db.models.jDateField(auto_now=True)),
                ('code', models.CharField(max_length=5)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_unit', models.CharField(choices=[('t', 'Toman'), ('p', 'Percent')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('valid_until', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('minimum_order_value', models.IntegerField(blank=True, null=True)),
                ('maximum_discount_amount', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='cart.orderinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
