# Generated by Django 4.2.1 on 2024-01-14 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0028_alter_cartdiscount_code_alter_categorydiscount_code_and_more"),
    ]

    operations = []
