# Generated by Django 4.2.1 on 2024-01-14 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0029_auto_20240114_0215"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderinfo",
            name="order_id",
        ),
    ]
