# Generated by Django 4.2.1 on 2023-06-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default'], 'verbose_name_plural': 'Addresses'},
        ),
    ]
