# Generated by Django 4.2.1 on 2023-05-18 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.",
                        regex="^0\\d{10}$",
                    )
                ],
            ),
        ),
    ]
