# Generated by Django 4.2.1 on 2023-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subproduct",
            name="size",
            field=models.CharField(
                choices=[
                    ("s", "Small"),
                    ("m", "Medium"),
                    ("l", "Large"),
                    ("xl", "Extra-Large"),
                    ("xxl", "2Extra-Large"),
                ],
                max_length=5,
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductSize",
        ),
    ]
