# Generated by Django 4.2.1 on 2023-05-18 22:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
