# Generated by Django 4.2.1 on 2023-05-15 17:24

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="shoppingsession",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                ("img", models.ImageField(blank=True, null=True, upload_to="_images")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
