# Generated by Django 4.2.1 on 2023-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_cart_is_deleted_alter_cartitem_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
