# Generated by Django 4.2.1 on 2023-05-18 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_productreview_product_alter_productreview_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="date",
        ),
    ]
