# Generated by Django 4.2.1 on 2023-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_subproduct_size_delete_productcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subproduct",
            name="price",
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="suppliers_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
