# Generated by Django 4.2.1 on 2023-05-21 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
