# Generated by Django 4.2.1 on 2023-05-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_productreview_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.productreview",
            ),
        ),
    ]
