# Generated by Django 4.2.1 on 2023-05-16 09:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_media_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dummy_date", django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
        ),
    ]
