# Generated by Django 4.2.1 on 2023-06-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subproduct_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
    ]
