# Generated by Django 4.2.1 on 2023-05-18 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0003_remove_subproduct_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("create_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("modified_date", django_jalali.db.models.jDateField(auto_now=True)),
                ("date", models.DateField()),
                ("rating", models.DecimalField(decimal_places=0, max_digits=5)),
                ("text", models.CharField(max_length=200)),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Dummy",
        ),
        migrations.RemoveField(
            model_name="subproduct",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="subproduct",
            name="retail_price",
        ),
        migrations.RemoveField(
            model_name="subproduct",
            name="suppliers_price",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop.category",
            ),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.AddField(
            model_name="subproduct",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.pricing",
            ),
        ),
    ]
