# Generated by Django 4.2.1 on 2023-05-16 09:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_dummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummy",
            name="dummy_date",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
