# Generated by Django 4.2.1 on 2023-06-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_orderinfo_order_id'),
        ('shop', '0004_alter_category_options_alter_media_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.orderinfo'),
        ),
    ]
