# Generated by Django 4.2.1 on 2023-05-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_remove_media_product_remove_pricing_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="price",
            field=models.IntegerField(null=True, verbose_name="Price of a Subproduct"),
        ),
        migrations.AddField(
            model_name="pricing",
            name="subproduct",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.subproduct",
            ),
        ),
    ]
