# Generated by Django 4.2.1 on 2023-05-18 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_productreview_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session_id",
        ),
    ]
