# Generated by Django 4.2.1 on 2023-05-17 06:23

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_dummy_dummy_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummy",
            name="dummy_date",
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
