# Generated by Django 4.2.1 on 2023-05-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_remove_cart_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subproduct",
            name="price",
        ),
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
