# Generated by Django 4.2.1 on 2023-05-22 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_pricing_price_pricing_subproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
