# Generated by Django 4.2.1 on 2023-05-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_alter_categorydiscount_coupon_code_and_more"),
        ("shop", "0007_remove_cartitem_cart_delete_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.orderinfo",
            ),
        ),
    ]
